steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image for removing the oldest VM with the service label
    args: [build, -t, $_GCR/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME, "."]
images: [$_GCR/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _GCR: us-docker.pkg.dev
