steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image for removing the oldest VM with the service label
    args: [build, -t, $_GCR/$PROJECT_ID/vm-cleanup/vm-cleanup, "."]
images: [$_GCR/$PROJECT_ID/vm-cleanup/vm-cleanup]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _GCR: ""
