steps:
  - name: python
    entrypoint: python
    args: [-m, pip, install, --upgrade, pip]
  - name: python
    entrypoint: python
    args: [-m, pip, install, -r, requirements.txt]
  - name: python
    entrypoint: python
    id: Removing the oldest VM with the service label
    args:
      [
        -m,
        cleanup,
        --project_id=$PROJECT_ID,
        --zone=$ZONE,
        --service_name_label=$_SERVICE_LABEL,
      ]
